### ISSUE TITLE
TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by leoj3n** [leoj3n/bitcentivez#1]
`npm run develop-static` works fine but `npm run develop-ssr` results in:

```console
Received client connection
Uncaught Exception
 TypeError: Cannot read property 'contains' of null
    at Array.<anonymous> (file:/Users/leoj/src/bitcentivez/client/node_modules/can-view-live/lib/core.js:70:41)
    at fire (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:143:19)
    at dispatchEvents (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:155:5)
    at Immediate.processBatch (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:77:5)
    at Immediate.<anonymous> (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/tasks.js:117:14)
    at Task.run (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:38:17)
    at Zone.runTask (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:183:14)
    at Immediate._onImmediate (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:284:15)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

Looks to be an issue with `can-zone` and `can-view-live`.

**Comment by leoj3n** [comment]
Similar `Cannot read property 'contains' of null` error when deployed to Heroku:

![image](https://user-images.githubusercontent.com/990216/46051198-968ecd00-c0fd-11e8-888c-3ef1d4cd4a23.png)

**Comment by leoj3n** [comment]
DoneJS Forum post asking for help regarding this:

https://forums.donejs.com/t/can-someone-please-take-a-look-at-this/969

**Comment by leoj3n** [comment]
`can-view-live` is `4.2.1`:

```console
$ npm ls can-view-live --prefix client
bitcentivez@0.0.1 /Users/leoj/src/bitcentivez
└─┬ can@5.11.0
  ├─┬ can-stache@4.12.0
  │ └── can-view-live@4.2.1  deduped
  ├─┬ can-stache-bindings@4.4.0
  │ └── can-view-live@4.2.1  deduped
  └── can-view-live@4.2.1
```

Let's get version `4.2.2` of `can-view-live`:

```console
$ rm -rf node_modules/ client/node_modules/ server/node_modules/
$ npm i --save github:canjs/canjs#greenkeeper/can-view-live-4.2.2 --prefix client
$ npm install
```

`can-view-live` is now updated from `4.2.1` to `4.2.2`:

```console
$ npm ls can-view-live --prefix client
bitcentivez-client@0.0.1 /Users/leoj/src/bitcentivez/client
└─┬ can@5.11.0 (github:canjs/canjs#0ffc3526d14cb5e8c366203049e75c1dbc34367d)
  ├─┬ can-stache@4.12.0
  │ └── can-view-live@4.2.2  deduped
  ├─┬ can-stache-bindings@4.4.0
  │ └── can-view-live@4.2.2  deduped
  └── can-view-live@4.2.2
```

Let's try `develop-ssr` with `can-view-live@4.2.2`:

```console
npm run develop-ssr
```

Unfortunately, it still results in a very similar error:

```console
Uncaught Exception
 TypeError: Cannot read property 'contains' of null
    at Array.<anonymous> (file:/Users/leoj/src/bitcentivez/client/node_modules/can-view-live/lib/attrs.js:104:40)
    at fire (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:143:19)
    at dispatchEvents (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:155:5)
    at Immediate.processBatch (file:/Users/leoj/src/bitcentivez/client/node_modules/can-dom-mutate/can-dom-mutate.js:77:5)
    at Immediate.<anonymous> (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/tasks.js:117:14)
    at Task.run (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:38:17)
    at Zone.runTask (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:183:14)
    at Immediate._onImmediate (/Users/leoj/src/bitcentivez/server/node_modules/can-zone/lib/zone.js:284:15)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

It looks like the `'contains'` error has moved from `can-view-live/lib/core.js:70:41` to `can-view-live/lib/attrs.js:104:40`. Not sure what to try next, or how to debug further.

**Comment by leoj3n** [comment]
Published fix: https://github.com/canjs/can-view-live/releases/tag/v4.2.3
